### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Victory0622** [PabloMessina/MedVQA#1]
Dear PabloMessina, I came across your work on MedVQA and am very interested in it. Could you please share the dataset link with me?

**Comment by PabloMessina** [comment]
Hello @Victory0622, what dataset are you referring to specifically?

**Comment by Victory0622** [comment]
Hello, Pablo Messina! mimiccxr and iuxray dataset. I am new to the MedVQA. Are there any materials or tutorials that you would recommend for study? Thank you very much.

**Comment by PabloMessina** [comment]
@Victory0622

- MIMIC-CXR: https://physionet.org/content/mimic-cxr/2.0.0/
- IU X-ray: https://openi.nlm.nih.gov/faq#collection
- Regarding materials or tutorials, that depends on your background knowledge and what you want to do concretely. As a general recommendation, ChatGPT can give you pretty good personalized advice for self-study: https://chat.openai.com/

**Comment by Victory0622** [comment]
Thank you
